### PR TITLE
Several build fixups

### PR DESCRIPTION
**Pull request by velichkov**
- Require cmake 3.2 or later 
- Add cmake options that enable/disable grcc compilation 
  cmake -DENABLE_GRCC=OFF ..
  cmake -DENABLE_GRGSM_LIVEMON=OFF ..
  cmake -DENABLE_GRGSM_LIVEMON_HEADLESS=OFF ..
- Fix the parallel build with cmake 3.11
- Add CentOS7 docker container 
- Add DEBIAN_FRONTEND=noninteractive 
  This suppress "debconf: unable to initialize frontend: Dialog" messages
- Check that pkg-config is available

### CODE REVIEW

File: swig/CMakeLists.txt [hunk 1]
```diff
@@ -28,6 +28,20 @@ endif()
 include(GrSwig)
 include(GrPython)
 
+function(GR_UNIQUE_TARGET desc)
```
Comment (ptrkrysik) [inline swig/CMakeLists.txt]: What is the purpose of this redefinition of GR_UNIQUE_TARGET? Does it speed up SWIG part. It would be great as it takes currently more time than the rest of compilation.

Comment (velichkov) [reply swig/CMakeLists.txt]: I should have documented this change better. I was trying to fix the parallel build on Fedora 26/27/28 using cmake 3.11.0/3.11.2 
```bash
# make -j 4
make[2]: *** No rule to make target 'swig/grgsm_swig.py', needed by 'swig/grgsm_swig.pyc'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:749: swig/CMakeFiles/pygen_swig_72fe6.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Built target pygen_python_bd098
[  2%] Built target grgsm_swig_swig_doc
[  4%] Building CXX object lib/CMakeFiles/grgsm.dir/flow_control/uplink_downlink_splitter_impl.cc.o
[  4%] Building CXX object lib/CMakeFiles/grgsm.dir/misc_utils/burst_file_sink_impl.cc.o
........
[ 39%] Building CXX object lib/CMakeFiles/grgsm.dir/trx/trx_burst_if_impl.cc.o
[ 40%] Linking CXX shared library libgrgsm-0.41.4git.so
[ 69%] Built target grgsm
make: *** [Makefile:141: all] Error 2
```
The strange thing is that I'm not able to reproduce this failure on Debian Testing with cmake 3.11.2.
I'm going to debug this problem some more and either amend the commit or drop it from this PR.

Comment (velichkov) [reply swig/CMakeLists.txt]: It turns out that in Debian the `gnuradio-dev` package distribute a modified version of the UseSWIG.cmake where the parallel build issue is fixed.  https://github.com/gnuradio/gnuradio/commit/99a09af05fda6d0bab0cf3724a1c6bf453c71bc7
```
$ dpkg -l gnuradio-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                            Version              Architecture         Description
+++-===============================-====================-====================-====================================================================
ii  gnuradio-dev:amd64              3.7.12.0-3           amd64                GNU Software Defined Radio toolkit development
$ dpkg -L gnuradio-dev  | grep UseSWIG.cmake
/usr/lib/x86_64-linux-gnu/cmake/gnuradio/UseSWIG.cmake
```
But in Fedora/CentOS/RHEL the `gnuradio-devel` package does not distribute such macro, they delete all cmake macros while building the package
https://src.fedoraproject.org/rpms/gnuradio/blob/master/f/gnuradio.spec#_150-152

So I've decided to copy the UseSWIG.cmake from the gnuradio repository (commit 4433a7703fe3f5713c2200a0f7c11b13510f34cc) into the local repository as there are copies of other gnuradio's macros there already.

**Comment by ptrkrysik** [comment]
Hi Vasil, I added changes in the build_system_changes branch. The branch also contains my changes of the grcc compilation. It would be If great you can have a look.

**Comment by velichkov** [comment]
Hi Piotr, 

> I added changes in the build_system_changes branch. The branch also contains my changes of the grcc compilation. It would be If great you can have a look.

Your changes looks good and I've just tested them successfully in ubuntu 14.04 with cmake 2.8.12.2.

```
$ git fetch
remote: Counting objects: 47, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 47 (delta 24), reused 47 (delta 24), pack-reused 0
Unpacking objects: 100% (47/47), done.
From https://github.com/ptrkrysik/gr-gsm
 + c16b35c...47c3e9b development -> origin/development  (forced update)
 * [new branch]      build_system_changes -> origin/build_system_changes
   4e4a92e..6463dc7  trx_hopping -> origin/trx_hopping
```
You have forced pushed the development branch which could be problematic for less experience git users, for example my other two pull requests now contain additional 9 commits because they are based on the old development branch, so I need to rebase them on the new development branch and do a force push.
